// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function toString(a) {
  return "ExactlyOne(" + a._0 + ")";
}

function runExactlyOne(a) {
  return a._0;
}

function mapExactlyOne(f, a) {
  return /* ExactlyOne */{
          _0: Curry._1(f, a._0)
        };
}

function bindExactlyOne(f, a) {
  return Curry._1(f, a._0);
}

exports.toString = toString;
exports.runExactlyOne = runExactlyOne;
exports.mapExactlyOne = mapExactlyOne;
exports.bindExactlyOne = bindExactlyOne;
/* No side effect */
