// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function toString(param) {
  return "ExactlyOne(" + (String(param[0]) + ")");
}

function runExactlyOne(param) {
  return param[0];
}

function mapExactlyOne(f, param) {
  return /* ExactlyOne */[Curry._1(f, param[0])];
}

function bindExactlyOne(f, param) {
  return Curry._1(f, param[0]);
}

exports.toString = toString;
exports.runExactlyOne = runExactlyOne;
exports.mapExactlyOne = mapExactlyOne;
exports.bindExactlyOne = bindExactlyOne;
/* No side effect */
