// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Listz$Data61Reason = require("./Listz.bs.js");
var Reader$Data61Reason = require("./Reader.bs.js");
var ExactlyOne$Data61Reason = require("./ExactlyOne.bs.js");

var ExactlyOneFunctor = {
  map: ExactlyOne$Data61Reason.mapExactlyOne
};

var ListzFunctor = {
  map: Listz$Data61Reason.map
};

function map(f, x) {
  if (x !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(x)));
  }
  
}

var OptionFunctor = {
  map: map
};

function MakeReaderFunctor(TYPE) {
  var ReaderFunctor = {
    map: Reader$Data61Reason.map
  };
  return {
          ReaderFunctor: ReaderFunctor
        };
}

exports.ExactlyOneFunctor = ExactlyOneFunctor;
exports.ListzFunctor = ListzFunctor;
exports.OptionFunctor = OptionFunctor;
exports.MakeReaderFunctor = MakeReaderFunctor;
/* Listz-Data61Reason Not a pure module */
