// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Listz$FpCourseReason = require("./Listz.bs.js");
var Reader$FpCourseReason = require("./Reader.bs.js");
var ExactlyOne$FpCourseReason = require("./ExactlyOne.bs.js");

var ExactlyOneFunctor = {
  map: ExactlyOne$FpCourseReason.mapExactlyOne
};

var ListzFunctor = {
  map: Listz$FpCourseReason.map
};

function map(f, x) {
  if (x !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(x)));
  }
  
}

var OptionFunctor = {
  map: map
};

function MakeReaderFunctor(TYPE) {
  var Functor = {
    map: Reader$FpCourseReason.map
  };
  return {
          Functor: Functor
        };
}

function MakeFunctionFunctor(TYPE) {
  var map = function (f, g, x) {
    return Curry._1(f, Curry._1(g, x));
  };
  var Functor = {
    map: map
  };
  return {
          Functor: Functor
        };
}

exports.ExactlyOneFunctor = ExactlyOneFunctor;
exports.ListzFunctor = ListzFunctor;
exports.OptionFunctor = OptionFunctor;
exports.MakeReaderFunctor = MakeReaderFunctor;
exports.MakeFunctionFunctor = MakeFunctionFunctor;
/* Listz-FpCourseReason Not a pure module */
