// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function run(param, env) {
  return Curry._1(param[0], env);
}

function $$return(a) {
  return /* Reader */[(function (_env) {
              return a;
            })];
}

function ask(param) {
  return /* Reader */[(function (env) {
              return env;
            })];
}

function local(f, m) {
  return /* Reader */[(function (env) {
              return run(m, Curry._1(f, env));
            })];
}

function map(f, m) {
  return /* Reader */[(function (env) {
              return Curry._1(f, run(m, env));
            })];
}

function bind(f, m) {
  return /* Reader */[(function (env) {
              return run(Curry._1(f, run(m, env)), env);
            })];
}

function $great$great$eq(m, f) {
  return bind(f, m);
}

exports.run = run;
exports.$$return = $$return;
exports.ask = ask;
exports.local = local;
exports.map = map;
exports.bind = bind;
exports.$great$great$eq = $great$great$eq;
/* No side effect */
