// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function run(r, env) {
  return Curry._1(r._0, env);
}

function $$return(a) {
  return /* Reader */{
          _0: (function (_env) {
              return a;
            })
        };
}

function ask(param) {
  return /* Reader */{
          _0: (function (env) {
              return env;
            })
        };
}

function local(f, r) {
  return /* Reader */{
          _0: (function (env) {
              return run(r, Curry._1(f, env));
            })
        };
}

function map(f, r) {
  return /* Reader */{
          _0: (function (env) {
              return Curry._1(f, run(r, env));
            })
        };
}

function bind(f, r) {
  return /* Reader */{
          _0: (function (env) {
              return run(Curry._1(f, run(r, env)), env);
            })
        };
}

function $great$great$eq(r, f) {
  return bind(f, r);
}

exports.run = run;
exports.$$return = $$return;
exports.ask = ask;
exports.local = local;
exports.map = map;
exports.bind = bind;
exports.$great$great$eq = $great$great$eq;
/* No side effect */
