// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function toString(value) {
  if (value.tag) {
    return "Value(" + (String(value[0]) + ")");
  } else {
    return "Error(" + (String(value[0]) + ")");
  }
}

function isError(value) {
  if (value.tag) {
    return false;
  } else {
    return true;
  }
}

function isValue(value) {
  return !isError(value);
}

function mapValidation(f, a) {
  if (a.tag) {
    return /* Value */Block.__(1, [Curry._1(f, a[0])]);
  } else {
    return /* Error */Block.__(0, [a[0]]);
  }
}

function bindValidation(f, a) {
  if (a.tag) {
    return Curry._1(f, a[0]);
  } else {
    return /* Error */Block.__(0, [a[0]]);
  }
}

function valueOr(a, b) {
  if (a.tag) {
    return a[0];
  } else {
    return b;
  }
}

function errorOr(a, b) {
  if (a.tag) {
    return b;
  } else {
    return a[0];
  }
}

exports.toString = toString;
exports.isError = isError;
exports.isValue = isValue;
exports.mapValidation = mapValidation;
exports.bindValidation = bindValidation;
exports.valueOr = valueOr;
exports.errorOr = errorOr;
/* No side effect */
