// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ExactlyOne$FpCourseReason = require("../src/ExactlyOne.bs.js");
var Applicative$FpCourseReason = require("../src/Applicative.bs.js");

Jest.describe("Functor", (function (param) {
        return Jest.describe("ExactlyOne", (function (param) {
                      return Jest.test("apply is correct", (function (param) {
                                    var f = /* ExactlyOne */[(function (param) {
                                          return 10 + param | 0;
                                        })];
                                    var result = Applicative$FpCourseReason.ExactlyOneApplicative.apply(f, /* ExactlyOne */[8]);
                                    return Jest.Expect.toBe(18, Jest.Expect.expect(ExactlyOne$FpCourseReason.runExactlyOne(result)));
                                  }));
                    }));
      }));

/*  Not a pure module */
